#version: "3.8"  

services:  # Cette ligne est ESSENTIELLE
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:  # Doit être indenté sous services:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  scraper:
    build: .
    container_name: scraper
    volumes:
      - .:/app
    depends_on:
      - mongo
      - elasticsearch
    command: ["sh", "-c", "./wait-for-it.sh elasticsearch:9200 -- python scripts/scraper.py"]


volumes:
  mongo_data:
  esdata: